env:
  global:
    - secure: "SVMOUmFKgDeaMNGfr4a4R7KuSoZdm312ysXHBwIlLVcq+Wg3vJB1CB+TZZXKTJYP+czWDb87Ma5GHbN+zfSSoTMGhG1MNGanyIuHcRalDzSqBDgsPukVR6RoMr//66MRgu+7uke/aDt8VrPNY1JzyL7MCkFsTqoCWBnc2t0hHbM="
    - secure: "AqyAyYlphHeAimee+xCyiRBP8qq8243si5/Zs24HOEqs5ZxF2BmitdRmPQw4CFCGX3K/PwO2Bt/2eehJPG5IQi0telYzPWCGPD9Q2B+AG45NVzuzzaHWCHVvO4h9lZly0WXK1ox38IsneMDoh1WumMfatV0MKH/x7jw2JGhLC40="

language: c

compiler: gcc

cache:
  - apt
  - bundler

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install packaging-dev
  - sudo pbuilder create --debootstrapopts --variant=buildd
  - wget http://ftp.gnu.org/gnu/hello/hello-2.9.tar.gz
  - sha256sum --check --status SHA256SUMS && mv -v hello-2.9.tar.gz hello_2.9.orig.tar.gz

script:
  - pushd hello
  - pdebuild --debbuildopts "-i -uc -us"
  - popd

after_success:
  - gem install deb-s3
  - deb-s3 upload --arch=amd64 --bucket=s3pa-mwhiteley-hello --codename=precise --access-key-id=${AWS_ACCESS_KEY_ID} --secret-access-key=${AWS_SECRET_ACCESS_KEY} --visibility=public /var/cache/pbuilder/result/hello_2.9-0ubuntu1_amd64.deb
